### PR TITLE
Added 2 mycoplasma testing fields. Fixes #120

### LINKED ISSUE #120: Mycoplasm testing field clarification
Confirm what the mycoplasma testing results (growing_conditions module) is reported as: binary yes/no? % contamination? something else?

### PR DESCRIPTION
**Pull request by malloryfreeberg**
### Changed
This change is to make the fields mycoplasma_testing_method and mycoplasma_testing_results enums. This is a major change.

### CODE REVIEW

**Comment by pnejad** [comment]
@malloryfreeberg  Maybe we could add two more enums?

1) Cell-based assays ( ex PlasmoTest)
2) Microbiological assays

**Comment by daniwelter** [comment]
@pnejad do you mean add two more fields that are enums or add more values to the two enums Mallory added? If it's new fields, would you  be able to supply definitions and values?

**Comment by pnejad** [comment]
@daniwelter  I meant to add two more fields to Mallory's current list of enums for 'mycoplasma_testing_method'.

**Comment by daniwelter** [comment]
@pnejad Gotcha :)

**Comment by malloryfreeberg** [comment]
@pnejad added :) can you approve and then @daniwelter can merge?

**Pull request merged**
