### PR TITLE
Process core field changes. Fixes #376 Fixes #377

### LINKED ISSUE #376: Rename field process_location to location
### Original request
1. <process_location>
**Which schema needs to be changed?**
Change to process_core.json
**What field in that schema need to be changed?**
process_location field
**What should the new field name be?**
Change to location
**Why is the change requested?**
Shortening.

### Consequences:

1. Location could be used in other contexts, e.g. contact or preservation_storage, which would overload the term
2. From a usability point of view, this doesn’t comply with the principles for: “recognition rather than recall”, “visibility of system status”, “error prevention” [https://www.nngroup.com/articles/ten-usability-heuristics/](https://www.nngroup.com/articles/ten-usability-heuristics/)  , as it might be ambiguous if not carrying the specific context (i.e. location could be for institute, sequencing centre, operator etc)
3. Breaking change for all downstream components

### LINKED ISSUE #377: Rename field operator_identity to operator
### Original request
1. <operator_identity>
**Which schema needs to be changed?**
Change to process_core.json
**What field in that schema need to be changed?**
operator_identity
**What should the new field name be?**
Change to operator
**Why is the change requested?**
Shortening

### Consequences: 

1. Breaking change for all downstream components
2. From a usability point of view, this doesn’t comply with the principles for: “recognition rather than recall”, “visibility of system status”, “error prevention” [https://www.nngroup.com/articles/ten-usability-heuristics/](https://www.nngroup.com/articles/ten-usability-heuristics/) , as it might be ambiguous if not carrying the specific context

### PR DESCRIPTION
**Pull request by willrockout**
Changed operator_identity and process_location names to operator and location in process core.

### CODE REVIEW

**Comment by malloryfreeberg** [comment]
I am withholding review until we discuss these particular changes on today's Metadata call.

**Comment by lauraclarke** [comment]
@malloryfreeberg what is the best way forward here. I think the operator idenity to operator change goes in but the process_location field is still under discusssion so needs to be held back

**Comment by malloryfreeberg** [comment]
This PR should really be for just 1 field change, since they are major changes and in 2 separate issues. @willrockout if you can revert the `process_location` change and update the `update_log.csv` file today, I can review/merge this tomorrow morning. If you don't get time today, I can just do it tomorrow and then review/merge. Also @cjvillar if you could add your review after Will's made the changes (since he tagged you) that would be great. We really should start following the procedure of not merging until all reviewers give their formal review.

**Comment by willrockout** [comment]
@malloryfreeberg All fixed should be good to go. @cjvillar can you review before Mallory merges.

**Comment by malloryfreeberg** [comment]
This PR can be merged once all tagged reviewers have approved (I'm looking at you, @cjvillar ).

**Pull request merged**
