### PR TITLE
Edit pullapprove config

### PR DESCRIPTION
**Pull request by mshadbolt**
- Removed pnejad from reviewers
- Added groups and reviewers from other components
- Changed conditions to allow merging into staging from other branches (I think)
- Removed notifications to other components

- Need 1 Reviewers to approve because this isn't a change to the schemas

### CODE REVIEW

**Comment by mshadbolt** [comment]
/pullapprove-test

```yaml
version: 3

# The following line breaks the yml - 404 page not found error
# extends: https://api.github.com/repos/example/pullapprove-config/contents/.pullapprove.yml

# If this conditions are not met, it will throw the 'unmet_status'.
pullapprove_conditions:
- condition: "not any(['release' in labels, 'hotfix' in labels])"
  unmet_status: success
  explanation: "Releases, security updates and hotfixes are allowed to merge in integration, staging and/or master"
- condition: "base.ref == 'develop' or '[Snyk]' in title"
  unmet_status: failure
  explanation: "No PRs from unknown branches can be merged into integration, staging or master"
- condition: "'on hold' not in labels"
  unmet_status: pending
  explanation: "PR review is on hold"
- condition: "'*[tT]ravis*' in check_runs.success"
  unmet_status: failure
  explanation: "Travis CI tests must pass before review starts"

notifications:
- when: pull_request.opened
  if: "author_association == 'CONTRIBUTOR'" # Only contributing authors get this message
  comment: |
    Hey @{{ author }}, thanks for the PR! The review will start once
    the tests and CI checks have passed.
- when: pullapprove.approved
  if: "author_association == 'CONTRIBUTOR'" # Only contributing authors get this message
  comment: "The review is completed. Thanks @{{ author }}!"
- when: pull_request.opened
  if: "'content' in labels and 'major' in body" # Notify the DCP for a major update
  comment: |
    Major metadata schema update, pinging @aaclan-ebi @NoopDog
    @hannes-ucsc @aherbst-broad . If no one objects, this will be merged on the
    following 5 working days.
groups:

  snyk-security-patches:
    conditions:
    - "'[Snyk]' in title"
    - "'Security' not in labels"
    reviewers:
      users:
      - ESapenaVentura
      - aaclan-ebi
      - jacobwindsor
      - yusra-haider
    reviews:
      required: 1
      request_order: shuffle
      
  azul-browser:
    conditions:
    - "'*[Tt]ravis*' in check_runs.successful"
    - "base.ref == 'develop'"
    - "'content' in labels"
    reviewers:
      users:
      - hannes-ucsc
      - NoopDog
    reviews:
      required: 1
      request: 1
     request_order: shuffle
  
  pipelines:
    conditions:
    - "'*[Tt]ravis*' in check_runs.successful"
    - "base.ref == 'develop'"
    - "'content' in labels"
    reviewers:
      users:
      -<insert lantern usernames>
    reviews:
      required: 1
      request: 1
      request_order: shuffle
  
  data_import:
    conditions:
    - "'*[Tt]ravis*' in check_runs.successful"
    - "base.ref == 'develop'"
    - "'content' in labels"
    reviewers:
      users:
      - aherbst-broad
    reviews:
      required: 1
      request: 1
      request_order: shuffle
    
  tdr:
    conditions:
    - "'*[Tt]ravis*' in check_runs.successful"
    - "base.ref == 'develop'"
    - "'content' in labels"
    reviewers:
      users:
      -<insert tdr usernames>
    reviews:
      required: 1
      request: 1
      request_order: shuffle

  metadata-updates-major-minor:  # group name
    conditions:  # the group is activated when all of these statements are true
    - "'*[Tt]ravis*' in check_runs.successful"
    - "base.ref == 'develop'"
    - "'major' in body or 'minor' in body" # major or minor change is indicated in body of PR
    - "'content' in labels"
    reviewers:  # people who can approve for this group
      users:
      - mshadbolt
      - ESapenaVentura
      - rays22
      - rays22
      - ami-day
      - ami-day
      - Wkt8
      - Wkt8
      - mshadbolt
      - willrockout
      - ESapenaVentura
      - rachadele
    reviews:  # settings for approval and reviewer selection
      required: 2
      request_order: shuffle  # reviewers will be chosen in a random order

  metadata-updates-patch:
    conditions:
    - "'*[Tt]ravis*' in check_runs.successful"
    - "base.ref == 'develop'"
    - "'patch' in body" # patch change is indicated in body of PR
    - "'content' in labels"
    reviewers:
      users:
        - mshadbolt
        - ESapenaVentura
        - rays22
        - rays22
        - ami-day
        - ami-day
        - Wkt8
        - Wkt8
        - mshadbolt
        - willrockout
        - ESapenaVentura
        - rachadele
    reviews:
      required: 1
      request_order: shuffle

  code-review:
    conditions:
    - "'*[Tt]ravis*' in check_runs.successful"
    - "base.ref == 'develop'"
    - "'*.py' in files or '*.js' in files or '*.yml' in files"
    reviewers:
      users:
      - mshadbolt
      - ESapenaVentura
      - rays22
      - ami-day
      - Wkt8
    reviews:
      required: 1
      request_order: shuffle
```

**Review by mshadbolt — COMMENTED** [review]
removed failed pullapprove config

**Review by mshadbolt — COMMENTED** [review]
/pullapprove-test

```yaml
version: 3

# The following line breaks the yml - 404 page not found error
# extends: https://api.github.com/repos/example/pullapprove-config/contents/.pullapprove.yml

# If this conditions are not met, it will throw the 'unmet_status'.
pullapprove_conditions:
- condition: "not any(['release' in labels, 'hotfix' in labels])"
  unmet_status: success
  explanation: "Releases, security updates and hotfixes are allowed to merge in integration, staging and/or master"
- condition: "base.ref == 'develop' or '[Snyk]' in title"
  unmet_status: failure
  explanation: "No PRs from unknown branches can be merged into integration, staging or master"
- condition: "'on hold' not in labels"
  unmet_status: pending
  explanation: "PR review is on hold"
- condition: "'*[tT]ravis*' in check_runs.success"
  unmet_status: failure
  explanation: "Travis CI tests must pass before review starts"

notifications:
- when: pull_request.opened
  if: "author_association == 'CONTRIBUTOR'" # Only contributing authors get this message
  comment: |
    Hey @{{ author }}, thanks for the PR! The review will start once
    the tests and CI checks have passed.
- when: pullapprove.approved
  if: "author_association == 'CONTRIBUTOR'" # Only contributing authors get this message
  comment: "The review is completed. Thanks @{{ author }}!"
- when: pull_request.opened
  if: "'content' in labels and 'major' in body" # Notify the DCP for a major update
  comment: |
    Major metadata schema update, pinging @aaclan-ebi @NoopDog
    @hannes-ucsc @aherbst-broad . If no one objects, this will be merged on the
    following 5 working days.
groups:

  snyk-security-patches:
    conditions:
    - "'[Snyk]' in title"
    - "'Security' not in labels"
    reviewers:
      users:
      - ESapenaVentura
      - aaclan-ebi
      - jacobwindsor
      - yusra-haider
    reviews:
      required: 1
      request_order: shuffle
      
  azul-browser:
    conditions:
    - "'*[Tt]ravis*' in check_runs.successful"
    - "base.ref == 'develop'"
    - "'content' in labels"
    reviewers:
      users:
      - hannes-ucsc
      - NoopDog
    reviews:
      required: 1
      request: 1
     request_order: shuffle
  
  pipelines:
    conditions:
    - "'*[Tt]ravis*' in check_runs.successful"
    - "base.ref == 'develop'"
    - "'content' in labels"
    reviewers:
      users:
      - kbergin
    reviews:
      required: 1
      request: 1
      request_order: shuffle
  
  data_import:
    conditions:
    - "'*[Tt]ravis*' in check_runs.successful"
    - "base.ref == 'develop'"
    - "'content' in labels"
    reviewers:
      users:
      - aherbst-broad
    reviews:
      required: 1
      request: 1
      request_order: shuffle
    
  tdr:
    conditions:
    - "'*[Tt]ravis*' in check_runs.successful"
    - "base.ref == 'develop'"
    - "'content' in labels"
    reviewers:
      users:
      - mshadbolt
    reviews:
      required: 1
      request: 1
      request_order: shuffle

  metadata-updates-major-minor:  # group name
    conditions:  # the group is activated when all of these statements are true
    - "'*[Tt]ravis*' in check_runs.successful"
    - "base.ref == 'develop'"
    - "'major' in body or 'minor' in body" # major or minor change is indicated in body of PR
    - "'content' in labels"
    reviewers:  # people who can approve for this group
      users:
      - mshadbolt
      - ESapenaVentura
      - rays22
      - rays22
      - ami-day
      - ami-day
      - Wkt8
      - Wkt8
      - mshadbolt
      - willrockout
      - ESapenaVentura
      - rachadele
    reviews:  # settings for approval and reviewer selection
      required: 2
      request_order: shuffle  # reviewers will be chosen in a random order

  metadata-updates-patch:
    conditions:
    - "'*[Tt]ravis*' in check_runs.successful"
    - "base.ref == 'develop'"
    - "'patch' in body" # patch change is indicated in body of PR
    - "'content' in labels"
    reviewers:
      users:
        - mshadbolt
        - ESapenaVentura
        - rays22
        - rays22
        - ami-day
        - ami-day
        - Wkt8
        - Wkt8
        - mshadbolt
        - willrockout
        - ESapenaVentura
        - rachadele
    reviews:
      required: 1
      request_order: shuffle

  code-review:
    conditions:
    - "'*[Tt]ravis*' in check_runs.successful"
    - "base.ref == 'develop'"
    - "'*.py' in files or '*.js' in files or '*.yml' in files"
    reviewers:
      users:
      - mshadbolt
      - ESapenaVentura
      - rays22
      - ami-day
      - Wkt8
    reviews:
      required: 1
      request_order: shuffle
```

**Review by mshadbolt — COMMENTED** [review]
removed failed pullapprove config

**Review by mshadbolt — COMMENTED** [review]
/pullapprove-test

```yaml
version: 3

# The following line breaks the yml - 404 page not found error
# extends: https://api.github.com/repos/example/pullapprove-config/contents/.pullapprove.yml

# If this conditions are not met, it will throw the 'unmet_status'.
pullapprove_conditions:
- condition: "not any(['release' in labels, 'hotfix' in labels])"
  unmet_status: success
  explanation: "Releases, security updates and hotfixes are allowed to merge in integration, staging and/or master"
- condition: "base.ref == 'develop' or '[Snyk]' in title"
  unmet_status: failure
  explanation: "No PRs from unknown branches can be merged into integration, staging or master"
- condition: "'on hold' not in labels"
  unmet_status: pending
  explanation: "PR review is on hold"
- condition: "'*[tT]ravis*' in check_runs.success"
  unmet_status: failure
  explanation: "Travis CI tests must pass before review starts"

notifications:
- when: pull_request.opened
  if: "author_association == 'CONTRIBUTOR'" # Only contributing authors get this message
  comment: |
    Hey @{{ author }}, thanks for the PR! The review will start once
    the tests and CI checks have passed.
- when: pullapprove.approved
  if: "author_association == 'CONTRIBUTOR'" # Only contributing authors get this message
  comment: "The review is completed. Thanks @{{ author }}!"
- when: pull_request.opened
  if: "'content' in labels and 'major' in body" # Notify the DCP for a major update
  comment: |
    Major metadata schema update, pinging @aaclan-ebi @NoopDog
    @hannes-ucsc @aherbst-broad . If no one objects, this will be merged on the
    following 5 working days.
groups:

  snyk-security-patches:
    conditions:
    - "'[Snyk]' in title"
    - "'Security' not in labels"
    reviewers:
      users:
      - ESapenaVentura
      - aaclan-ebi
      - jacobwindsor
      - yusra-haider
    reviews:
      required: 1
      request_order: shuffle
      
  azul-browser:
    conditions:
    - "'*[Tt]ravis*' in check_runs.successful"
    - "base.ref == 'develop'"
    - "'content' in labels"
    reviewers:
      users:
      - hannes-ucsc
      - NoopDog
    reviews:
      required: 1
      request: 1
      request_order: shuffle
  
  pipelines:
    conditions:
    - "'*[Tt]ravis*' in check_runs.successful"
    - "base.ref == 'develop'"
    - "'content' in labels"
    reviewers:
      users:
      - kbergin
    reviews:
      required: 1
      request: 1
      request_order: shuffle
  
  data_import:
    conditions:
    - "'*[Tt]ravis*' in check_runs.successful"
    - "base.ref == 'develop'"
    - "'content' in labels"
    reviewers:
      users:
      - aherbst-broad
    reviews:
      required: 1
      request: 1
      request_order: shuffle
    
  tdr:
    conditions:
    - "'*[Tt]ravis*' in check_runs.successful"
    - "base.ref == 'develop'"
    - "'content' in labels"
    reviewers:
      users:
      - mshadbolt
    reviews:
      required: 1
      request: 1
      request_order: shuffle

  metadata-updates-major-minor:  # group name
    conditions:  # the group is activated when all of these statements are true
    - "'*[Tt]ravis*' in check_runs.successful"
    - "base.ref == 'develop'"
    - "'major' in body or 'minor' in body" # major or minor change is indicated in body of PR
    - "'content' in labels"
    reviewers:  # people who can approve for this group
      users:
      - mshadbolt
      - ESapenaVentura
      - rays22
      - rays22
      - ami-day
      - ami-day
      - Wkt8
      - Wkt8
      - mshadbolt
      - willrockout
      - ESapenaVentura
      - rachadele
    reviews:  # settings for approval and reviewer selection
      required: 2
      request_order: shuffle  # reviewers will be chosen in a random order

  metadata-updates-patch:
    conditions:
    - "'*[Tt]ravis*' in check_runs.successful"
    - "base.ref == 'develop'"
    - "'patch' in body" # patch change is indicated in body of PR
    - "'content' in labels"
    reviewers:
      users:
        - mshadbolt
        - ESapenaVentura
        - rays22
        - rays22
        - ami-day
        - ami-day
        - Wkt8
        - Wkt8
        - mshadbolt
        - willrockout
        - ESapenaVentura
        - rachadele
    reviews:
      required: 1
      request_order: shuffle

  code-review:
    conditions:
    - "'*[Tt]ravis*' in check_runs.successful"
    - "base.ref == 'develop'"
    - "'*.py' in files or '*.js' in files or '*.yml' in files"
    reviewers:
      users:
      - mshadbolt
      - ESapenaVentura
      - rays22
      - ami-day
      - Wkt8
    reviews:
      required: 1
      request_order: shuffle
```

**Review by ESapenaVentura — APPROVED** [review]
LGTM! 👍

**Comment by ESapenaVentura** [comment]
Meeerging

**Pull request merged**
