### PR TITLE
Updated pullapprove config file. Fixes #1109.

### LINKED ISSUE #1109: Update pullapprove config to not ask for reviews
Update the pullapprove config yaml file to keep it updated with changes in the DCP Wrangler and metadata team.

 

As a DCP data wrangler team member who reviews pull requests, I would like to update the config file to reflect the latest changes on the metadata/wrangler team.

**Acceptance Criteria**

 
- [ ] Pullapprove config yaml is adjusted with updated information.

### PR DESCRIPTION
**Pull request by ESapenaVentura**
This is a code enhancement to the config file.

Fixed old unexpected bejaviour(s):
- Now it won't fail automatically if trying to merge a release, security update or hotfix to a branch other than develop (It will still fail if trying to merge from a branch to any environment other than develop).

Added new functionalities:
- Notification of major schema updates to @maniarathi @aaclan-ebi @MDunitz @NoopDog @brianraymor @jahilton @jychien @jlzamanian @samanehsan @hannes-ucsc @kislyuk
- Added code review group
- Added security updates review group and automatic notification to @ESapenaVentura  when Snyk opens a PR.

### Reviews requested

- Need 1 Reviewers to approve because this is a code update
- Last Reviewer to review/approve, merge by 06/09/2019

### CODE REVIEW

**Comment by ESapenaVentura** [comment]
@HumanCellAtlas/wranglers In order to test this, you can copy the contents of the config file, and paste it as a comment on a review like
/pullapprove-test
```
<content_of_config>
```

More information on the validator [here](https://docs.pullapprove.com/config-validator/)

**Comment by ESapenaVentura** [comment]
/pullapprove-test
```version: 3

# The following line breaks the yml - 404 page not found error
# extends: https://api.github.com/repos/example/pullapprove-config/contents/.pullapprove.yml

# If this conditions are not met, it will throw the 'unmet_status'.
pullapprove_conditions:
- condition: "base.ref in ['integration', 'staging', 'master'] and labels in ['Security', 'release', 'hotfix']"
  unmet_status: failure
  explanation: "Only releases, hotfixes and security updates are allowed to merge to environments higher than develop"
- condition: "'on hold' not in labels"
  unmet_status: pending
  explanation: "PR review is on hold"
- condition: "'*travis*' in statuses.successful"
  unmet_status: failure
  explanation: "Travis CI tests must pass before review starts"

notifications:
- when: pull_request.opened
  if: "author_association == 'CONTRIBUTOR'" # Only contributing authors get this message
  comment: |
    Hey @{{ author }}, thanks for the PR! The review will start once
    the tests and CI checks have passed.
- when: pullapprove.approved
  if: "author_association == 'CONTRIBUTOR'" # Only contributing authors get this message
  comment: "The review is completed. Thanks @{{ author }}!"
- when: pull_request.opened
  if: "'[Snyk]' in title"   # Notify Enrique to assign security label
  comment: "@ESapenaVentura please put the 'Security' label"
- when: pull_request.opened
  if: "'content' in labels and 'major' in body" # Notify the DCP for a major update
  comment: |
    Major metadata schema update, pinging @maniarathi @aaclan-ebi @MDunitz @NoopDog @brianraymor
    @jahilton @jychien @jlzamanian @samanehsan @hannes-ucsc @kislyuk . If No one objects, this will be merged on the
    following 5 working days.
groups:

  snyk-security-patches:
    conditions:
    - "'[Snyk]' in title"
    - "'Security' not in labels"
    reviewers:
      users:
      - ESapenaVentura
      - simonjupp
      - diekhans
      - willrockout
      - rolando-ebi
    reviews:
      required: 1
      request_order: shuffle

  metadata-updates-major-minor:  # group name
    conditions:  # the group is activated when all of these statements are true
    - "'*travis*' in statuses.succeeded"
    - "base.ref == 'develop'"
    - "'major' in body or 'minor' in body" # major or minor change is indicated in body of PR
    - "'content' in labels"
    reviewers:  # people who can approve for this group
      users:
      - zperova
      - mshadbolt
      - ESapenaVentura
      - zperova
      - mshadbolt
      - ESapenaVentura
      - willrockout
      - cjvillar
    reviews:  # settings for approval and reviewer selection
      required: 2
      request_order: shuffle  # reviewers will be chosen in a random order

  metadata-updates-patch:
    conditions:
    - "'*travis*' in statuses.succeeded"
    - "base.ref == 'develop'"
    - "'patch' in body" # patch change is indicated in body of PR
    - "'content' in labels"
    reviewers:
      users:
      - zperova
      - mshadbolt
      - ESapenaVentura
      - zperova
      - mshadbolt
      - ESapenaVentura
      - willrockout
      - cjvillar
    reviews:
      required: 1
      request_order: shuffle

  code-review:
    conditions:
    - "'*travis*' in statuses.succeeded"
    - "base.ref == 'develop'"
    - "'*.py' in files or '*.js' in files or '*.yml' in files"
    reviewers:
      users:
      - mshadbolt
      - ESapenaVentura
      - willrockout
      - cjvillar
    reviews:
      required: 1
      request_order: shuffle
```

**Comment by ESapenaVentura** [comment]
@HumanCellAtlas/wranglers Still need to meeeerge :)

**Comment by ESapenaVentura** [comment]
@HumanCellAtlas/wranglers I need a reviewer to merge, please!

**Comment by mshadbolt** [comment]
Sorry Enrique, I can review on monday, was a bit difficult to know it was ready since we got so many notifications since the first one

**Comment by ESapenaVentura** [comment]
Sorry, I know this is kind of a mess, but it is the only way to try the config file, and you can't delete pullapprove comments afterwards!

Review when you can, there's no hurry, I just wanted to remind the wranglers :)

**Comment by mshadbolt** [comment]
@ESapenaVentura walked me through the updates he made to the pullapprove config file and they all sound like great improvements so merging.

**Pull request merged**
