### PR TITLE
Added estimated_cell_count field to project. Fixes #1337

### LINKED ISSUE #1337: Add project level organ/assay type/cell count to project_core
**For which schema is a change/update being suggested?**

project_core.json

**What should the change/update be?**

I would like to add project level organ, organ_part and assay/technology fields to the schema that provide a convenient way of understanding summary aspects of the project at a glance. This field could be filled in manually or automatically filled when a project is imported into ingest from the metadata available in the spreadsheet.

This update constitutes a minor change to the project schema

**What new field(s) need to be changed/added?**

#### project organs
* Field name: organs
* Field description: A list of organs that were studied in this project
* Field type: List of `organ_ontology` objects
* Required: no
* Examples: NA
* CV or enum: no

#### project organ parts
* Field name: organ_parts
* Field description: A list of specific organ parts that were studied in this project.
* Field type: list of `organ_part_ontology` objects
* Required: no
* Examples: NA
* CV or enum: no

#### project assays
* Field name: assays
* Field description: A list of the assays that were used in this project
* Field type: list of `process_type_ontology` objects
* Required: no
* Examples: NA
* CV or enum: no

#### project cell_counts
* Field name: estimated_cell_count
* Field description: An estimated number of cells in this project
* Field type: int
* Required: no
* Examples: 10000;2000000
* CV or enum: no

**Why is the change requested?**

To allow users an easy way to see key information about the project at the project level

### PR DESCRIPTION
**Pull request by ESapenaVentura**
### Release notes

For `type/project/project` schema:
- Added non-required field "estimated_cell_count" HumanCellAtlas/metadata-schema#1337

### CODE REVIEW

**Review by kbergin — APPROVED** [review]
Would someone be able to comment back with why we are adding these fields (or link to issues that explain the motivation?) I'm approving because I see they are all optional additions, but I want to understand if we will want to start using any of these fields to support downstream use cases.

**Comment by ESapenaVentura** [comment]
Hi @kbergin !

So, the general idea behind these fields is to be able to provide with a project level summary in the metadata.

Also, with this update we are providing an extra field we didn't have before: `hca_publication_status` which in the future can be used by the browser to highlight projects that contain HCA publications

The `estimated_cell_count` field will help wranglers to include a cell count based on a total estimate, which is usually available, vs including an estimated count by cell suspension, which is most of the times not available and leads to the `unspecified` number of cells in a lot of projects

I don't think the rest of the added optional fields are very useful for any DCP component at the moment, but they will help providing quick overviews for either
1. Third-party apps gathering metadata from DCP projects
2. Computational scientists batch downloading metadata will be able to categorise easily by looking at the project (vs filtering in the browser)

I hope this answer throws some clarity on the issues!

**Review by theathorn — COMMENTED** [review]
I am unclear as to the motivation for these changes or how it solves a problem. The Data Browser "Project Information" tab (displayed whenever a user clicks on a project already has the summary information  for "Organ", "Organ Part", "Library Construction Method" and "Cell Count Estimate", all without the user applying any filters. These summary values are calculated by Azul. Introducing redundancies into the metadata would potentially introduce inconsistencies and, since the proposed additions would not be visible in the Data Browser or in any of its metadata download facilities, it's unclear how the user would access the new summaries. Programmatic users can already obtain the summary info (in the same manner as the Data Browser does). If desired, the UI could also be enhanced to allow download of project summary data.
There may be a case for "estimated cell count" where the "estimated cell count by suspension" is "Unspecified" but an overall count for the project is known by the submitters/wranglers.

**Comment by hannes-ucsc** [comment]
Agree with Trevor. This PR constitutes a pretty significant deviation from the current design: until now there is no redundancy in the schema, it is fully normalized. It is Azul that denormalizes the metadata and that's a good thing because it much easier to change the schema of Azul's index, than it is to change the metadata schema since the latter usually requires updates to the metadata itself. 

Is the added convenience for clients that consume the metadata directly (I reckon there aren't that many of that sort) worth the complications this PR introduces? Complications like "How does Azul index these properties?" or "What do we do if there are discrepancies between the hard-coded aggregations and what comes out of Azul's denormalization?" We have so much work to do, why spend time on a problem that's already solved?

**Comment by NoopDog** [comment]
At our post-demo meeting today, we decided we would:

1. Remove the fields `organ`, `organ_parts`, and `assays` from this PR. These were being added to support the wrangler ingest spreadsheet replacement tool and a workaround has been determined. 

1. We would split out `hca_publication_status` into its own PR to decouple it from the remaining changed field `estimated_cell_count`. We will do this because the work _can_ be decoupled and the `hca_publication_status` modeling will require additional discussion. 

1. For `estimated_cell_count`, we will add this to the project schema and make it not required initially. This will allow us to selectively backfill projects that have missing `estimated_cell_count` information at the library level.  Azul and other metadata clients will use the `project.estimated_cell_count` if it exists, and otherwise, determine the project's `estimated_cell_count` by summing the `estimated_cell_count`s for a project's libraries.

Please update to cover anything I have that is incorrect or any significant detail I have omitted.

**Comment by ESapenaVentura** [comment]
I have updated the PR - Now it only contains the agreed changes

As per the other change (HCA publication status), I'll tag everyone in the slack channel comment as agreed on the DCP2 doc, but it's here https://github.com/HumanCellAtlas/metadata-schema/pull/1396

**Review by NoopDog — APPROVED** [review]

**Review by aherbst-broad — APPROVED** [review]

**Review by theathorn — APPROVED** [review]

**Review by ruchim — APPROVED** [review]
latest version LGTM

**Review by hannes-ucsc — APPROVED** [review]
LGTM. As we discussed, Azul needs to incorporate this into its index and consolidate the number specified here with corresponding number found in the individual cell suspensions in a project. I assume that we will want the summary cell count 

image

to reflect both counts, those found in project entities as well as those found in cell suspension. If a particular project defines both a project-level cell count and one found on individual cell suspensions, we will use the sum of the latter and ignore the project-level cell count.

This isn't going to be trivial since all of our code assumes that cell count estimates are extracted from cell suspensions only. To test our implementation changes, we request that this property is added to the schema test data repository. 

I approve on that condition.

**Comment by clairerye** [comment]
> LGTM. As we discussed, Azul needs to incorporate this into its index and consolidate the number specified here with corresponding number found in the individual cell suspensions in a project. I assume that we will want the summary cell count
> 
> image
> 
> to reflect both counts, those found in project entities as well as those found in cell suspensions. If a particular project defines both a project-level cell count and one found on individual cell suspensions, we will use the sum of the latter and ignore the project-level cell count.
> 
> This isn't going to be trivial since all of our code assumes that cell count estimates are extracted from cell suspensions only. To test our implementation changes, we request that this property is added to the schema test data repository.
> 
> I approve on that condition.

Thanks! Yes I agree that is the behaviour we would like. Once this is merged we can create the test data and let you know when its available as a PR against the test data repo. As with the other PR, do you want another full round of approval on the staging to master PR?

**Comment by hannes-ucsc** [comment]
I don't think a PR against master is necessary. In the unlikely case that we find issues with the schema changes when we review the test metadata changes, we would do another staging PR with adjustments.

**Review by amnonkhen — APPROVED** [review]

**Pull request merged**
