### PR TITLE
Fixed travis notifications and pre-commit hooks. Fixes #1025

### LINKED ISSUE #1025: Fix travis notifications and pre-commit hooks
**Description**

 

As a DCP member that commits into this repository, I would like to add changes to `.travis.yml`, `src/add_docs.sh` and `.pre-commit-config.yaml`, in order to fix some bugs found.

**Acceptance Criteria**

 
 
- [ ] `.travis.yml`: Change current document to have this at the end:
```
notifications:
  slack:
    rooms:
      - secure: UfBGxFNJsQaXqZxgdMT0SFEsKlaMT+J4XlKIO/Cwaomex3LkkT4TPW0S1qYehgzGeY8SBGVjilod8nhLl2+eRs3Fm5Q2YtxG0+fHLQOEHbnkpTcRjhHGJav51/msTLWsj5lXKveMNOaeFB1Q5qGGIQWsqMmwEyuDRVaAhnWAn2ueisOvXQrsCbauSvrhg8wfQ5fc4oteVyj9QvIY2+U2ZiVEr8PZGjs+y8LqPUeIrkBbGJFd8DdWoKATAvVnKZirEzF5pIBlAUsQjgYcCef9Cl/kqcvO9yUjbYh5MPlK/j1UEOnif7lKBcM+BIv1m1AaoaDtbgdJFbVW8wKVLp1zrMvsJpKMm3VFBsfU2MruQgJA8F+QgtVX8jJQXINUuhYD8U6pfrf/AFW1LJmy4R6iTkHLVBpkrPhf8A99Zymur7Bbn2eZGGgmJ2E0At/a18Kh7HMLVRsB8dy9hi42aiLDiJOqCDcZva7Rb8KgbWoplXrdFSEzh+xHJmDMnXiumDO0iVhNLH+Yx5Fpkrh+WSLaqCPFfYA0suOojGXr+waDRyW+HIfuS4bc0IpVhwJ+nR1SYzKkG5X0N1d1XUxkmNHDIKc1wFcxCKRAJDz9JHTWiM2nRZeOs+VCzqSpn5nApw/Gk9YmFhIir/GK1eaN1sa76wCsaCT8m7DpuoWkTryGSpU=
    on_failure: change
    on_success: change
```
- [ ] `src/add_docs.sh`: Call `src/human_readable_json.py` from inside the executable
- [ ] `src/add_docs.sh`: Change name to its new function.

### PR DESCRIPTION
**Pull request by ESapenaVentura**
### Release notes

For `.pre-commit-config.yaml`:
- Deleted `human_readable_json` pre-commit hook as it's now called from within the `generate_md_docs` hook.
- Changed `add_docs` hook id to `generate_md_docs` for clarity
- Changed `Adding generated markdown docs to commit` hook name to `Generating markdown documents`

For `add_docs.sh` document:
- Added `python3 src/human_readable_json.py` before git add
- Changed name to `generate_md_docs.sh`
- Moved to `.githooks` folder. It feels a better place for the pre-commit hooks.

For `.travis.yml`:
- Fixed a syntax error where it wasn't notifying updates to the slack channel.

### How to test new changes

- Open branch in your computer
- Make sure you have the pre-commit package installed
- Make breaking errors in schema (e.g., `biomaterial_id` to `biomaterial_false`) 
- Commit. Should commit properly, executing `human_readable_json` on the commit (This tests the changes to the pre-commit hooks).
- Push. Travis build should fail and a notification will be sent to the slack (This tests changes to `travis.yml`)
- Change back to previous state, commit and push. This time the travis build will pass and a notification will be sent to slack.

### Reviews requested

- Need 1 Reviewers to approve because this is a minor scripts update
- Last Reviewer to review/approve, merge changes by 18/06/2019

### CODE REVIEW

**Comment by ESapenaVentura** [comment]
@malloryfreeberg If this looks good to you, I can merge it myself.

**Comment by malloryfreeberg** [comment]
@ESapenaVentura how are you testing your changes? How can I test the changes you've made?

**Comment by ESapenaVentura** [comment]
> @ESapenaVentura how are you testing your changes? How can I test the changes you've made?

Sorry, forgot to add that. I just edited the PR to showcase how to test this.

**Comment by ESapenaVentura** [comment]
Tagged @zperova as a reviewer to test this. Remember to install pre-commit first! instructions [here](https://github.com/HumanCellAtlas/metadata-schema/issues/1032#issuecomment-501206375)

**Comment by zperova** [comment]
This works. Should I merge now?

**Comment by malloryfreeberg** [comment]
@zperova yes, please!

**Pull request merged**
