### PR TITLE
Standardize protocol method ontology

### LINKED ISSUE #319: Standardize protocol method ontology
1. Which schema needs be changed?
    1. `collection_protocol.json`
    1. `dissociation_protocol.json`
    1. `enrichment_protocol.json`
    1. `library_preparation_protocol.json`
    1. `sequencing_protocol.json`

1. What field(s) in that schema need to be changed/added?
    1. `collection_protocol.collection_method` and `collection_protocol.protocol_type`
    1. `dissociation_protocol.dissociation_method` and `dissociation_protocol.protocol_type`
    1. `enrichment_protocol.enrichment_method` and `enrichment_protocol.protocol_type`
    1.  `library_preparation_protocol.protocol_type`
    1. `sequencing_protocol.protocol_type` and a **new** `sequencing_protocol.sequencing_approach`

1. What should the change/addition be?
    1. `collection_method`: change from enum to referencing `process_type_ontology.json`, make required
    1. `dissociation_method`: change from enum to referencing `process_type_ontology.json`
    1. `enrichment_method`: change from referencing specific enrichment_process ontology to more generic `process_type_ontology.json`
    1. `sequencing_protocol.sequencing_approach`: a new field
        - description: The general approach for sequencing.
        - type: object referencing "module/ontology/library_construction_ontology.json"
        - user_friendly: Sequencing approach
        - required: Yes
    1. Remove all `protocol_type` fields in the schemas listed in 1.

1. Why is the change requested?
The `*_method`/`library_construction_approach` fields and `protocol_type` fields were basically duplicating information. We became aware of this duplication after the process --> protocol field migration. We will keep the `*_method`/`library_construction_approach` field names as these are clearer, but we will point to either the generic `process_type_ontology.json` ontology module or the specific library_preparation and sequencing ontology modules. These `*_method`/`*_approach` fields should all be required.

### PR DESCRIPTION
**Pull request by daniwelter**
Refactored protocol types to remove duplication between *_method and protocol_type, and addition of sequencing_ontology module. Fixes #319

### CODE REVIEW

**Comment by kbergin** [comment]
@samanehsan if you could just check if we use any of the fields that are being updated? See Mallory's summary message in slack here: https://humancellatlas.slack.com/files/U6CB89VLJ/FB0UQQ65U/HCA_Metadata_Standard_Proposed_Major_Update__Standardize_ontologies_for_protocol_methods

**Comment by samanehsan** [comment]
@kbergin we're using the `dissociation_method` field in our subscription queries, for example: https://github.com/HumanCellAtlas/lira/blob/master/scripts/v5_queries/smartseq2-query.json#L25

Since this field was changed to object in this PR, it looks like we would change our query to `dissociation_method.text`: https://github.com/HumanCellAtlas/metadata-schema/blob/abc9fa30fd4da41dae1e94e53f08fb50e401ebc6/json_schema/module/ontology/process_type_ontology.json#L22. @malloryfreeberg @daniwelter please correct me if I'm wrong here!

**Comment by kbergin** [comment]
Thank you for looking at this, @samanehsan !

**Comment by malloryfreeberg** [comment]
@samanehsan @kbergin Yes, we are proposing to govern this field with an ontology - which has the benefit of being a controlled vocabulary so that in the future you will know exactly what to match on :) The subscription query can either match on `dissociation_method.text` or on `dissociation_method.ontology`, the latter being the curie for the value in `.text`. 

The line `"files.process_json.processes.content.biomaterial_collection.dissociation_process.dissociation_method": "FACS"` in the subscription query should be changed to either:

 `...dissociation_method.text": "fluorescence-activated cell sorting"`

-or-

`...dissociation_method.ontology": "EFO:0009108"`

The ontology validation that will occur in ingest will ensure that all bundles including FACS dissociation protocols will have these values in these fields. @daniwelter please correct me if I'm wrong about ontology validation. Thanks for being on top of things @samanehsan !

**Comment by malloryfreeberg** [comment]
On a related note, the `dissociation_method` changes - which are currently in the develop branch and can be tested at schema.dev.data.humancellatlas.org - also include the process --> protocol change, which basically means a `s/process/protocol/` replacement will need to happen on all the subscription queries. There is more info on the process --> protocol change in [this PR](https://github.com/HumanCellAtlas/metadata-schema/pull/301), and we will be discussing on Monday's metadata call.

**Comment by samanehsan** [comment]
Thanks @malloryfreeberg!

**Pull request merged**
