### PR TITLE
Added example spreadsheets and graphs. Fixes #1165

### LINKED ISSUE #1165: Make example spreadsheets and their graphs for the Metadata section of the Data Portal
**Description**

We need to provide Dave with the content for the Metadata sections on the Data Portal in order to improve user's experience of finding relevant information about HCA metadata. 

As a data contributor, I would like to see an empty template and an example template to understand how to fill in my metadata for submission to the HCA-DCP.

Example and empty templates should be stored in metadata-schema/examples/spreadsheets/current/

**Acceptance criteria:**

- [x] empty template for 10x project is ready 
- [x] example template for 10x project is ready
- [x] graph corresponding to the example template for 10x is ready
- [x] emplty template for SS2 project is ready
- [x] example template for SS2 project is ready
- [ ] graph corresponding to the example template for SS2 is ready

### PR DESCRIPTION
**Pull request by ESapenaVentura**
### Release notes

No schema changes, added example spreadsheets for 10X and SS2 experiments as well as moved the old ones to "v6" in the archived folder.
 

### Reviews requested

- Need wranglers to take a look and see if they would add/delete anything from those spreadsheets or if they are good to go.
- Whoever wants to merge it after review will be appreciated

### CODE REVIEW

**Comment by mshadbolt** [comment]
you tagged the wrong issue in the commit messages

**Comment by ESapenaVentura** [comment]
Ugh, I miss-clicked, yeah. It's #1165

**Comment by ESapenaVentura** [comment]
Also, the SS2 graph is still not up, I need to be able to upload the spreadsheet (It's throwing a bizarre error with the importer)

**Comment by mshadbolt** [comment]
I think it would be worth using a much simpler example for the SS2 experiment, possibly limiting it to a 96 well plate.

**Comment by zperova** [comment]
10x template looks good and the graph as well! I agree with @mshadbolt for a much simpler SS2 experiment. I don't think having >1500 sequence files in an example template is very useful - we should aim for less scrolling - if we can't avoid the horizontal scrolling, at least we can minimize the vertical.

**Comment by ESapenaVentura** [comment]
Another point taken from the discussion with @gabsie is to change the graph style to use the asset objects in [here](https://drive.google.com/drive/folders/1XuRUMuIDCQuOqVtdk8MDujiRRtL0nxxW)

**Comment by ESapenaVentura** [comment]
Sincerely, I have no idea how to manipulate `.svg` files so I don't think I will be able to do it without it taking it way too much time. Do you have any idea of who could help me @gabsie ?

**Comment by ESapenaVentura** [comment]
- Updated SS2 experiment to only have 6 read files per cell suspension
- After some workaround, finally got to generate the graph.

I still need to generate the graph being compliant with the design chosen for the data portal, but I will need help from someone who has some experience with svg to update the graph with the assets.

**Comment by mshadbolt** [comment]
@ESapenaVentura I have some experience working with svg files and can help with making the graphs prettier and compliant with website branding, I will make a ticket :)

**Comment by ESapenaVentura** [comment]
Thanks!

**Comment by lauraclarke** [comment]
@ESapenaVentura it would be great to get this merged or closed

**Comment by ESapenaVentura** [comment]
I will work on the PR's tomorrow and see if it's valuable to merge them or it's better to close them at this point.

**Comment by ESapenaVentura** [comment]
I have corrected the SS2 and 10X to show the proper user-friendly names.

Given all the changes to the graph validator, creating an SS2 user-friendly graph will take ages. I propose we leave the 10x graph and come back to this when we have more news about how are we going to show the metadata schema to the community.

If @zperova , @mshadbolt and @lauraclarke are ok with this I will proceed to merge this today

**Comment by mshadbolt** [comment]
seems reasonable to me

**Pull request merged**
