### PR TITLE
Committer document updates for PR review process. Fixes #800.

### LINKED ISSUE #800: Update committer.md with policy for PRs
**Description**

 

Clarify the Committer document process regarding making, reviewing, and merging PRs. The documentation should include the following:
- [x] Person who makes the PR is "responsible"
- [x] Reviewer count
    - [x] Patch/bug fix: 1 Reviewer
    - [x] Minor: 2 Reviewers
    - [x] Major: 2 Reviewers
- [x] Time frame
    - [x] Patch/bug fix: 3 working days
    - [x] Minor: 5 working days
    - [x] Major: 5 working days
- [x] First reviewer to review and tag last reviewer
- [x] Last reviewer to review and to merge
- [x] If a named reviewer can’t do the review in the time frame, they are responsible for unassigning themselves, assigning a replacement reviewer and notifying the new reviewer in a tagged comment in the PR.

**Acceptance Criteria**

  
- [x] Updates to the committer.md doc

### PR DESCRIPTION
**Pull request by malloryfreeberg**
### Release notes

- Update to committer document for the process of reviewing and merging PRs.

### Reviews requested

- Need all metadata team members to approve because this is an update to the PR review process
- Last Reviewer to review/approve, merge changes by Tues Feb 12

### CODE REVIEW

**Comment by malloryfreeberg** [comment]
> May I suggest we do this:
> 
> <Major, minor, patch> update thus requires of reviewers
> OR
> Needs of reviewers as is a <major, minor, patch> update
> Unless you mean something different by the

Re-worded. Sound better?

**Comment by zperova** [comment]
yes thank you @malloryfreeberg Asking for my own sake :)

**Comment by malloryfreeberg** [comment]
@willrockout @cjvillar @pnejad @hewgreen please note that you have until the end of the day today (Feb 12) to approve these changes.

**Comment by malloryfreeberg** [comment]
Missing 2 reviews, but I'm merging anyway.

**Pull request merged**
