### PR TITLE
Added schema_version field to core and biomaterial modules.

### PR DESCRIPTION
**Pull request by malloryfreeberg**
- Re-ordered attributes in analysis_bundle.json
- Grammar updates to ingest.json
- Core entities
  - Re-ordered attributes
  - Added schema_version property
  - Replaced specific words with generic words (e.g. sample/donor with biomaterial) where appropriate
  - Updated some descriptions
 - Module entities
   - Re-ordered attributes
   - Removed call to empty definitions
   - Added schema_version property
   - Fixed incorrect titles and descriptions (due to copy/paste)
   - Added module for non-human fields
 - Type entities
   - Re-ordered attributes
   - Added schema_version property
   - Fixed incorrect titles and descriptions (due to copy/paste)

### CODE REVIEW

**Comment by malloryfreeberg** [comment]
@daniwelter I'm only partially through adding schema_version to everything. Feel free to merge but please keep this branch open.

**Comment by daniwelter** [comment]
@malloryfreeberg Give me a shout when you're done and I'll merge them all in one go

**Comment by malloryfreeberg** [comment]
@daniwelter ready to merge!

**Comment by malloryfreeberg** [comment]
@daniwelter and the branch can be deleted, too.

**Pull request merged**
