### PR TITLE
Change organ_part to an array. Fixes #648.

### LINKED ISSUE #648: Update organ_part text/ontology fields to arrays.
**For which schema is a change/update being suggested?**

I would like to request a change to the specimen_from_organism.json schema.

**What should the change/update be?**

I would like to update the organ part text and ontology fields to accept arrays.

**What new field(s) need to be changed/added?**

No new fields would need to be added just a type change from object to array.

**Why is the change requested?**

As a data generator, I want to be able to list out all the organ parts that I have pooled together so that data consumers can try an separate the cells into there respective parts.

### PR DESCRIPTION
**Pull request by malloryfreeberg**
### Release notes

For specimen_from_organism.json:
- Change organ_part to array. Fixes #648.

### Reviews requested

- Need 2 Reviewers to approve because this is a major change
- Last to review/approve, merge changes by Friday March 8

### CODE REVIEW

**Comment by malloryfreeberg** [comment]
@hannes-ucsc we are planning a change to rename `organ_part` to `organ_parts` and to make it an array of objects (formerly just an object). Does this change require a coordinated update to the metadata-api and/or Azul?

**Comment by hannes-ucsc** [comment]
> Does this change require a coordinated update to the metadata-api and/or Azul?

Yes. This one would be a little bit more involved than the organoid and estimated_cell_count changes, but not much. Tracked here: https://github.com/DataBiosphere/azul/issues/699

**Comment by hannes-ucsc** [comment]
Is it intentional that `model_organ_part` in organoid stays singular?

Is the intention to support multiple parts from the same organ?

**Comment by hannes-ucsc** [comment]
This is out on production now.

**Comment by hannes-ucsc** [comment]
Ignore previous comment. It was made in error.

**Comment by hannes-ucsc** [comment]
Azul and Data Browser support this on `integration` now.

**Pull request merged**
