### PR TITLE
Fixed file_content_ontology module graph_restriction and examples. Fixes #1037

### LINKED ISSUE #1037: file_content_ontology classes IDs should be lower cas
Identifiers in the EDAM ontology are lower case, so class IDs in the `classes` restriction and examples should all be lower case. See https://ontology.dev.data.humancellatlas.org/ontologies/edam/terms?iri=http%3A%2F%2Fedamontology.org%2Fdata_0006 for examples

### PR DESCRIPTION
**Pull request by ESapenaVentura**
### Release notes

For `file_content_ontology` schema:
- `ontology`:
   - `graph_restriction`:
      - `classes`: class is now lowercased, as the identifier in the edam database
   - `examples`: Examples are now lowercased, as the identifier in the edam database
 

### Reviews requested

- Need 1 Reviewers to approve because this is a patch update
- Last Reviewer to review/approve, merge changes by 14/06/2019

### CODE REVIEW

**Comment by malloryfreeberg** [comment]
@willrockout or @cjvillar could one of you take this one? We have EMBL-EBI all day tomorrow and I'm also busy prepping for sessions for the F2F.

**Comment by malloryfreeberg** [comment]
@willrockout @cjvillar could one of you take this for me, please?

**Comment by ESapenaVentura** [comment]
@cjvillar @willrockout Pinging, we need a reviewer, please! :)

**Comment by malloryfreeberg** [comment]
@willrockout please review and merge this PR.

**Pull request merged**
