### PR TITLE
Add Optimus test spreadsheet

### PR DESCRIPTION
**Pull request by samanehsan**
### Release notes

Add Optimus metadata spreadsheet for testing the pipeline in the DCP integration test.
 

### Reviews requested

- Need <> Reviewers to approve because <>
- Last to review/approve, merge changes

### CODE REVIEW

**Comment by malloryfreeberg** [comment]
Hi @samanehsan ! Thanks for opening a PR :) I took a look at the optimus sheet and added the `nucleic_acid_source` field to the Library Preparation Protocol tab with the value "single cell". I'm assuming this field is needed to match the subscription query?

Also a Q: Will this Optimus sheet replace the current 10x sheet? Wondering if we will need to maintain all 3 sheets now or just the SS2 and the new Optimus sheet.

By eye I saw that there were changes to the sequence files (names and checksums) and the estimated cell count. Is there anything else of interest that was changed in the Optimus sheet? Thanks!

**Comment by samanehsan** [comment]
Thanks for catching that @malloryfreeberg! It looks like the metadata in this spreadsheet is outdated (it still says `library_construction_approach` instead of `library_construction_method` and has the wrong value for end bias). I'll start over from the latest 10x spreadsheet that is in dev and just modify the sequence files (names and checksums) and the estimated cell count. 

This will replace the current 10x spreadsheet, and I was planning on removing that after making sure everything works in the new optimus integration test!

**Comment by malloryfreeberg** [comment]
@samanehsan sounds good! Happy to merge tomorrow if you can get it done today :)

**Comment by samanehsan** [comment]
Thanks @malloryfreeberg! It's updated now :octocat:

**Comment by malloryfreeberg** [comment]
Updated spreadsheet validates in dev environment.

**Pull request merged**
