### PR TITLE
 Expand disease ontology to include phenotype - Fixes #1460 

### LINKED ISSUE #1460: Expand disease ontology to include phenotype
**For which schema is a change/update being suggested?**

I would like to request an update to the `module/ontology/disease_ontology.json` schema.

**What should the change/update be?**

Currently, we are restricted to ontology terms which are a from:
- obo:mondo which are a subclass of MONDO:0000001 (Mondo Disease Ontology)
- obo:efo which are a subclass of PATO:0000461 (Normal)

We would like to add a new branch for phenotypic observations which are not strictly a disease but have clinical relevance and are of interest for reaserch.
We should expand the ontology term restrictions for disease_ontology to include 'phenotype' (exact branch tbd - it shouldn't be just human phenotype?).

This update constitutes a minor change to the schema(s) it affects.

**What new field(s) need to be changed/added?**

``` 
"graph_restriction":  {
                "ontologies" : ["obo:mondo", "obo:efo"],
                "classes": ["MONDO:0000001", "PATO:0000461"],`
```
**Why is the change requested?**

This change will allow contributors to report clinically signigcant phenotype observation in a way that is searchable

### PR DESCRIPTION
**Pull request by idazucchi**
Schema update priority ticket with explanation on the change: https://github.com/HumanCellAtlas/metadata-schema/issues/1460

### Release notes

For module/ontology/disease_ontology schema:
- changed restrictions to include `phenotype` branch in the allowed terms.
 

### Reviews requested

- This is a minor update
- Last Reviewer to review/approve, merge changes by 27/05/2022

### CODE REVIEW

**Review by ESapenaVentura — APPROVED** [review]
LGTM 👍

**Review by hannes-ucsc — APPROVED** [review]

**Comment by ncalvanese1** [comment]
This all looks good to me from the importer side!

**Comment by ruchim** [comment]
does it still make sense for the category to be called "disease" if the values in that category are "disease" + "phenotype"? It sounds to me like phenotype is the more generic term, and disease is the more specific one. If that line of thought makes sense, we'd want to re-name this filter in the UI to say "phenotype". I'm not a data modeling expert, so please take this with a grain of salt/skepticism.

**Review by ruchim — APPROVED** [review]
The changes look technically right. I'd love if we can continue the discussion around how this expanded definition of accepted ontologies may impact the researcher experience at the HCA portal and if its worthwhile to re-classify any filters.

**Review by amnonkhen — APPROVED** [review]

**Comment by idazucchi** [comment]
@ruchim 
We discussed the possibility of renaming the disease field between the wrangler, and ultimately we agreed that it still makes sense to keep the name disease. Our intent with the phenotype ontology is to represent conditions that indicate a deviation from the normal, healthy status. For example we might want to use the term Liver fibrosis, which indicates the presence of scar tissue in the liver. On its own phenotype is an extremely broad term which doesn’t necessarily refer to unhealthy status, so it would not be indicative of what can be found in that field

**Comment by willrockout** [comment]
@idazucchi @ESapenaVentura I think this update may have broken something in ingest related to ontology lookups. After fixing a linking issue with this projects submission 135f7f5c-4a85-4bcf-9f7c-4f035ff1e428 we've started getting the below error for a number of biomaterials:
Screen Shot 2022-05-24 at 12 06 46 PM

**Pull request merged**
