### PR TITLE
Imaging target channel made an array. Fixes Issue#596

### PR DESCRIPTION
**Pull request by zperova**
The channel field in the Imaging_target module has been made an array. Fixes Issue#596

Run the `src/schemas_are_valid_json.py` and `src/json_examples_validate_against_schema.py` scripts.

Changed update_log.

### CODE REVIEW

**Comment by malloryfreeberg** [comment]
@zperova just a note: the associated issue won't close automatically when this PR is merged up to master because there isn't a commit statement in the correct format. `Fixes Issue#596.` is present in one of the commit statements but the format should be `Fixes #596.` for the automatic closing to work.

Not a problem for now. We can always close the issue manually.

**Comment by zperova** [comment]
Thanks, @malloryfreeberg I will make sure to close this one and another one that has the same commit message.

**Comment by hewgreen** [comment]
This was merged to dev incorrectly so the merge was reversed. @zperova can you make a new PR for this? We should make sure we are following the correct procedure when we have clarified the docs.

**Comment by zperova** [comment]
@hewgreen the last step of the `Specific how-to for making changes` section in committers.md mentions that pre-release is done by the Reviewer. Unfortunately, it doesn't say that in the release_process.md itself. 
Ticket here https://github.com/HumanCellAtlas/metadata-schema/issues/627

**Comment by hewgreen** [comment]
All sorted now anyway. Merged and branch closed.

**Pull request merged**
