### PR TITLE
Add estimated cell count to project.json. Fixes #1343

### LINKED ISSUE #1343: Add estimated_cell_count to project.json
**For which schema is a change/update being suggested?**

project/project.json type schema

**What should the change/update be?**

Add the field `estimated_cell_count` to project schema so a project level estimate of cells is easily available to data consumers. 

This update constitutes a minor change to the schema(s) it affects.

**What new field(s) need to be changed/added?**

* Field name: estimated_cell_count
* Field description: A rough estimate of the total number of cells analysed in this project.
* Field type: integer.
* Required: no
* Examples: 46472,10000000

**Why is the change requested?**

To be able to see a rough estimate of analysed cells per project, often filled from a line in the abstract of a publication, e.g. "We analysed x cells to discover all these things about cell biology"

### PR DESCRIPTION
**Pull request by mshadbolt**
### Release notes

For type/project.json schema:
- Add optional estimated_cell_count field to record project level cell count
 

### Reviews requested

- Need 2 Reviewers to approve because this is a minor update
- Last Reviewer to review/approve, merge changes by Monday, March 8th

### CODE REVIEW

**Review by rays22 — APPROVED** [review]
Looks all right.

**Comment by mshadbolt** [comment]
@willrockout  as the deadline for review has passed, are you able to either review this PR or let us know if you do not have capacity to do so and we will assign other wranglers to review. Thanks!

**Comment by willrockout** [comment]
@mshadbolt So trying I'm to do this PR but there seems to be a problem with the release_prepare.py script. I'm getting a list index out of range error. Have you guys encountered this problem?

**Comment by mshadbolt** [comment]
hi @willrockout, thanks for the review and merge attempt. Yes you are right, I was getting a weird error too. I have attempted to fix it in the release_prepare script but I am going to get @ESapenaVentura to check he thinks the fix I made looks ok before we merge this. 

We may also need to get further approvals from other components as per the revised metadata schema process that was discussed this week.

**Comment by ESapenaVentura** [comment]
I have reverted the changes to the release prepare script

The index out of range error was caused because there was a missing quotation mark. If that was fixed, there was another error:

```
Traceback (most recent call last):
  File "release_prepare.py", line 159, in <module>
    updated_versions = releasePrep.updateVersions(content_log)
  File "release_prepare.py", line 58, in updateVersions
    versionUpdates = versionUpdater.updateVersions(True)
  File "/Users/enrique/HumanCellAtlas/metadata-schema/src/version_update.py", line 50, in updateVersions
    new_version = self.incrementVersion(old_version, self.update_type)
  File "/Users/enrique/HumanCellAtlas/metadata-schema/src/version_update.py", line 114, in incrementVersion
    elements = version.split(".")
```

And this was caused because the `update_log.csv` was not pointing to the proper path (`type/project` instead of `type/project/project`)

Fixing those 2 errors and running the script worked fine! So I don't think we need (At least for now!) any update to this script

**Review by ESapenaVentura — APPROVED** [review]
LGTM 👍

**Comment by mshadbolt** [comment]
thanks for the review and debugging!

**Review by willrockout — APPROVED** [review]

**Pull request merged**
