### PR TITLE
Updated 4 fields in ipsc_induction_protocol. Fixes #926.

### LINKED ISSUE #926: Updates to multiple fields in `ipsc_induction_protocol.json` schema
**For which schema is a change/update being suggested?**

I would like to request an update to the `ipsc_induction_protocol.json` schema.

**What should the change/update be?**

- [x] remove `ipsc_induction_produced_in_house` field to remove redundancy (`process.location`) (#459)
- [x] change `ipsc_induction_method ` to `method` to remove redundancy ("ipsc_induction")
- [x] change `ipsc_induction_factors` to `factors` to remove redundancy ("ipsc_induction") 
- [x] change `protocol_reagents` to `reagents` to remove redundancy ("ipsc_induction")

**What new field(s) need to be changed/added?**

Above.

**Why is the change requested?**

Adhere to Style Guide.

### PR DESCRIPTION
**Pull request by malloryfreeberg**
### Release notes

For ipsc_induction_protocol.json schema:
- Changed ipsc_induction_method to method. Fixes #926.
- Changed ipsc_induction_factors to factors. Fixes #926.
- Changed protocol_reagents to reagents. Fixes #926.
- Removed ipsc_induction_produced_in_house. Fixes #926.
 
### Reviews requested

- Need 2 Reviewers to approve because this is a major update with changes to property_migrations.json
- Last Reviewer to review/approve, merge changes by **Tuesday April 16**

### CODE REVIEW

**Comment by malloryfreeberg** [comment]
> I still think 'factors', even using full dot notation (ipsc_induction_protocol.factors) is a confusing field name

Another option is to use `induction_factors` so it would be `ipsc_induction_protocol.induction_factors`. Hoping the u-f name and definition make this most clear.

**Comment by zperova** [comment]
or reprogramming factors?

**Comment by malloryfreeberg** [comment]
> or reprogramming factors? in case you don't want to have induction in there too many times

reprogramming sounds good to me. @pnejad ?

**Comment by zperova** [comment]
@pnejad what is your opinion on `reprogramming_factors`?

**Comment by daniwelter** [comment]
@zperova There is now an extra script in the release script that adds the correct version number to the property migrations file at release. If you're confident that you have the right number for everything, just leave it in, but if you'd like to test the script, replace the version numbers for the new property migrations with blank quotes.

**Comment by pnejad** [comment]
@zperova @malloryfreeberg  reprogramming_factors is perfect! That is also the term we use in MISCE.

**Pull request merged**
