### PR TITLE
Added optional doi field to project. Fixes #997.

### LINKED ISSUE #997: Add project-level DOI field
The project needs a new optional field to store the project DOI. This DOI will be assigned by Biostudies

In future, this may become a required field but right now it is best to start as optional for a number of reasons

* Field name: biostudies_doi
* Field description: A DOI as assigned by the Biostudies database for this project
* Field type: string (not sure if this needs to be string or url)
* Required: no
* Examples: https://doi.org/10.6084/m9.figshare.8179490.v2

Note this example is from figshare so doesn't reflect what our DOIs will look

* CV or enum: no

This is needed as DOIs are going to be assigned to facilitate the citability of our datasets by providing permanent URLs which point to records about each HCA project and these DOIs need to be displayed in the data browser

### PR DESCRIPTION
**Pull request by malloryfreeberg**
### Release notes

For project.json schema:
- Added optional doi field. Fixes #997.
 

### Reviews requested

- Need 2 Reviewers to approve because this is a minor update
- Last Reviewer to review/approve, merge changes by **Wednesday June 12**

### CODE REVIEW

**Comment by malloryfreeberg** [comment]
@zperova @ESapenaVentura you've been pinged for review :)

**Comment by malloryfreeberg** [comment]
@ESapenaVentura @zperova please hold off on merging as there has been a question from Laura in the ticket https://github.com/HumanCellAtlas/metadata-schema/issues/997

**Comment by lauraclarke** [comment]
So I would leave this ticket on hold for now as there is an open question if Biostudies is the right solution for DOI assignment.

Back to the original question. I specified biostudies_doi so there would be no surprise about the fact the DOI resolved to a biostudies location and not somewhere within the HCA web space just as we are specific about the publication DOI or the protocol DOI I would like to be specific about the biostudies DOI so there are no surprises for users

**Comment by malloryfreeberg** [comment]
Closing this PR so that it doesn't accidentally get merged. We can open a new PR when we are sure what the change will be. Discussion happening in https://github.com/HumanCellAtlas/metadata-schema/issues/997

**Comment by diekhans** [comment]
DOIs are intended to be globally unique and resolvable.  This is
achieved by registrant being the prefix of the DOI.  Specifying
the registrant in the field name is redundant.

I also find it confusing, as DOIs themselves answer the question
of where it resolves.

What type of resource a DOI resolves to is defined by the type
of record containing the DOI.  A publication doi should be in a
record about publications.  There is no need for redundant within
the field name.

**Comment by malloryfreeberg** [comment]
Please comment on the issue (https://github.com/HumanCellAtlas/metadata-schema/issues/997) not this closed PR.

**Pull request closed without merging**
