### PR TITLE
Changed protocol type in links schema to enum. Fixes #1333

### LINKED ISSUE #1333: `protocol_type` in links schema should be an enum
… with an entry for each of the valid schema types for protocols.

https://github.com/HumanCellAtlas/metadata-schema/blob/90b0ac22def50d35538891c6d145d07077a8f93a/json_schema/system/links.json#L71

Would have prevented https://humancellatlas.slack.com/archives/C01360XN04S/p1603433805210700

### PR DESCRIPTION
**Pull request by ESapenaVentura**
### Release notes

For `system/links.json` schema:
- `protocol_type`: Changed from free string to enum of values 
 

Also not related to the schema update but I issued a quick hotfix for the schema linter (Addressed in issue #1294 )

### Reviews requested

- Need 2 Reviewers to approve because this is a major update 
- Last Reviewer to review/approve, merge changes by 29/02/2021

### CODE REVIEW

**Comment by mshadbolt** [comment]
the PR looks good to me but as predicted, Travis build is failing, will try to have a look at it.

I also noticed while reviewing that we have the non-typed protocol schema https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/type/protocol/protocol.json
Is that something we made at some point before deciding to make explicitly typed schemas? Do we still need it?

**Comment by mshadbolt** [comment]
I made a PR (#1341 ) that updates the ols url in the travis test which I believe was causing to fail, not sure if it makes more sense to review and merge that one first then merge this one once travis tests succeed?

**Comment by mshadbolt** [comment]
Also would it be standard to add a pass and a fail test for this change that we made? i.e. add json that has a value not in the enum list, and one that is?

**Review by mshadbolt — APPROVED** [review]
Looks good to me, will need another review before merging to develop, added Ray and Hannes in case he wants to review as the original requester of the change.

**Comment by ESapenaVentura** [comment]
I will delete the change I made to travis and rebase to make sure the changes we made to the tests will be reflected

Other than that, you're right, we need a "fail/pass" test for this schema as well

**Comment by mshadbolt** [comment]
@rays22 are you able to please review this PR so that we can merge it if it looks ok to you. Thanks!

**Review by rays22 — APPROVED** [review]
The links.json and ols_api changes look all right to me.

**Review by hannes-ucsc — APPROVED** [review]

**Pull request merged**
