### PR TITLE
Metadata schema style updates

### PR DESCRIPTION
**Pull request by malloryfreeberg**
- Updates to documentation in donor_organism schema
- Updates to documentation in state_of_specimen schema
- Tagged relevant issues

### CODE REVIEW

**Comment by malloryfreeberg** [comment]
@daniwelter can you merge me please :)

**Comment by malloryfreeberg** [comment]
@daniwelter Did you forget to run the `release_prepare.py` script before merging this PR? I rebased to develop for another PR, and the contents of the update_log.csv were as in this PR, not empty. Also, the versions and changelog have'nt been updated as per these changes. We might need to do a hotfix in develop to update `versions.json` and `changelog.md`.

**Comment by daniwelter** [comment]
I thought I did but clearly I must have forgotten. Do you want me to reopen and rerun or did you own PR fix it?

**Comment by malloryfreeberg** [comment]
I'll make a new PR and then ask you to merge it.

**Comment by malloryfreeberg** [comment]
@daniwelter new PR here (https://github.com/HumanCellAtlas/metadata-schema/pull/437/)

**Pull request merged**
