### PR TITLE
[WIP] Release schemas from develop to master

### PR DESCRIPTION
**Pull request by malloryfreeberg**
**New schemas**
- module/process/sequencing/10x
- system/links
- type/file/supplementary_file
- type/process/analysis/analysis_process

**Changed schemas**
- module/process/sequencing/smartseq2 -> module/process/sequencing/plate_based_sequencing
- bundle/ingest_audit -> system/provenance

**Removed schemas**
- bundle/*

**New fields**
- module/biomaterial/growth_conditions: feeder_layer_type
- module/project/contact: corresponding_contributor
- type/*: provenance
- type/file/sequence_file: technical_replicate_group
- type/biomaterial/cell_suspension: plate_based_sequencing
- type/protocol/sequencing/sequencing_protocol: 10x
- type/protocol/biomaterial_collection/ipsc_induction_protocol: ipsc_induction_factors

**Changed fields**
- core/process/process_core: operator_identity -> operator
- core/project/project_core: project_shortname -> project_short_name
- module/biomaterial/familial_relationship: is_child_of -> parent
- module/biomaterial/familial_relationship: is_parent_of -> child
- module/biomaterial/familial_relationship: is_sibling_of -> sibling
- type/biomaterial/donor_organism: biological_sex -> sex
- module/process/sequencing/plate_based_sequencing: well_name -> well_id
- system/provenance: submissionDate -> submission_date
- system/provenance: updateDate -> update_date
- type/protocol/sequencing/sequencing_protocol: paired_ends -> paired_end
- type/protocol/biomaterial_collection/dissociation_protocol: nucleic_acid_source -> type/protocol/sequencing/library_preparation_protocol: nucleic_acid_source
- type/protocol/analysis/analysis_protocol -> type/process/analysis/analysis_process: inputs, reference_bundle, tasks, timestamp_stop_utc, input_bundles, outputs, timestamp_start_utc, analysis_run_type

**Removed fields**
- module/process/sequencing/smartseq2: well_row
- module/process/sequencing/smartseq2: well_column

**Change requirement status**
- module/project/contact: institution -> REQUIRED
- module/project/contact: email -> NOT REQUIRED

**Updates to schema documentation (examples, user-friendly names, descriptions)**

**Updates to documentation in docs/ folder**

**Updates to example spreadsheets/JSON in examples/ folder**

**Updates to GitHub issue templates**

**Updates to repo test scripts/files**

### CODE REVIEW

**Comment by malloryfreeberg** [comment]
@daniwelter @hewgreen @willrockout @cjvillar @pnejad we need to discuss when we want to do this. We should merge some of these now, and maybe do a merge once a week leading up to August 31st.

**Comment by daniwelter** [comment]
Any particular reason we're not rolling this through the standard dev > integration > staging > master process?

**Comment by malloryfreeberg** [comment]
Because we're not continuing with the integration and staging environments moving forward, and I don't think any components other than ingest actually point to integration/staging. The DCP needs to decide before Aug 31 whether all components' envs will point to master, or whether component envs point to the corresponding envs.

**Comment by malloryfreeberg** [comment]
@cjvillar @pnejad @willrockout @daniwelter @hewgreen @zperova I suggest we promote develop to integration tomorrow to get these last large chunk of changes in while the integration test is still failing. We can then discuss when to promote to staging and then master - probably early next week after making an announcement. Thoughts?

**Pull request merged**
